apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: ratesentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root123"
            - name: MYSQL_DATABASE
              value: "rate_sentinel_db"
            - name: MYSQL_USER
              value: "ratesentinel"
            - name: MYSQL_PASSWORD
              value: "ratesentinel123"
          ports:
            - containerPort: 3306
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: ratesentinel
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306